### ISSUE TITLE
[FEATURE] Import and Export in different locale

### ISSUE THREAD

**Issue by dylanwuyoufu** [Baboo7/strapi-plugin-import-export-entries#13] opened 2022-06-23 05:41 UTC
Currently, data can only be imported / exported with default locale (language). how can it work with other languages/locales if using this plugin?

**Comment by Baboo7** [comment] 2022-06-23 15:03
I just tried and it works well when I export/import entries with multiple languages.
Are you talking about the relations of the entries?

**Comment by dylanwuyoufu** [comment] 2022-06-24 07:39
> I just tried and it works well when I export/import entries with multiple languages. Are you talking about the relations of the entries?

I mean that this plugin cannot work in the multiple languages (locales) site. Import / Export function can only use in default locale.

**Comment by Baboo7** [comment] 2022-06-24 08:15
Are you using a version of the plugin >= `1.5.0`? I tested to import / export an entry with locales and it works as expected

**Comment by dylanwuyoufu** [comment] 2022-06-24 12:16
> Are you using a version of the plugin >= `1.5.0`? I tested to import / export an entry with locales and it works as expected Also, did you check if the 2nd locale was enabled on the server where you're trying to import?

Yes, I are using latest version of this plugin ^1.5.0. Please see the following attachments.
![image](https://user-images.githubusercontent.com/5267874/175531848-3b29dddd-07d0-4365-a410-d668d5552ce7.png)
![image](https://user-images.githubusercontent.com/5267874/175531893-ca5a4676-f447-41dd-a22f-ff9b644ad55b.png)
![image](https://user-images.githubusercontent.com/5267874/175531938-9e1a6b1c-33fe-4a42-86e3-99daf6d97780.png)
![image](https://user-images.githubusercontent.com/5267874/175531988-de24a277-09e9-402e-b020-fc604b8eb023.png)
Always loading....

![image](https://user-images.githubusercontent.com/5267874/175532081-3e9dc285-cf3a-41fb-983c-b1134b95bec9.png)
Only English data (default locale), cannot export other language data to csv file

**Comment by Baboo7** [comment] 2022-06-27 14:17
This is strange. I tested with version `1.6.0` with multiple locales including Chinese and the export works fine on my side for both json and csv.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/15690915/175956237-48ce91c3-8b3c-4d1d-83e3-2efe3faeb84e.png">
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/15690915/175956510-abe7e975-85bf-4fe7-8fc4-db25d9aac57a.png">

Do you have any error displayed in the browser console or in the server logs?

**Comment by Baboo7** [comment] 2022-06-27 14:36
Plus a new version `1.6.1` has been published to export localizations (among others). Do you still face the issue with this version?

**Comment by dylanwuyoufu** [comment] 2022-06-30 07:06
> Plus a new version `1.6.1` has been published to export localizations (among others). Do you still face the issue with this version?

Yes, the issue is still in there. What is the version of node js you used? I use the nodejs which is version 14.18.1

**Comment by Baboo7** [comment] 2022-06-30 12:47
I'm using node version `16.14.0`

**Comment by dylanwuyoufu** [comment] 2022-07-01 05:33
> I'm using node version `16.14.0`

![image](https://user-images.githubusercontent.com/5267874/176829972-c6605364-073f-415e-b1f1-44792431cc98.png)
I switch to node version 16.14. 0. However, the import & export issue has not been fixed.

![image](https://user-images.githubusercontent.com/5267874/176830107-15d53658-8c25-4de7-8e59-64c7bc825470.png)
![image](https://user-images.githubusercontent.com/5267874/176830140-50c6ec2e-d679-42ca-aa06-ffba0c0a530e.png)

As shown in the above images, only default locale data can be export or import in strapi.

**Comment by Baboo7** [comment] 2022-07-01 09:03
The id is actually the correct one. When a language is chosen from the content type panel, the id displayed is the one of the selected localization, not the one of the entry itself (which is the id of the default localization)

**Comment by Baboo7** [comment] 2022-07-02 09:06
@dylanwuyoufu about the issue of the editor loading indefinitely you mentioned above, please refer to version `1.6.3` and the updated [installation doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#installation) to fix it.

**Comment by Baboo7** [comment] 2022-07-31 21:21
I'm closing this issue since I can not reproduce it

**Closed by Baboo7** 2022-07-31 21:21 UTC

**Comment by SalahAdDin** [comment] 2022-10-08 14:59
@Baboo7 Well, it is not clear even to me.

I'm trying to export my data and it always comes in English:
```
[
	{
		"id": 1,
		"name": "Back-End Development",
		"slug": "back-end-development",
		"description": "All the projects related to Back-end Development that I have done throughout my career as a systems and computer engineer.",
		"createdAt": "2022-10-08T12:35:38.019Z",
		"updatedAt": "2022-10-08T14:10:05.640Z",
		"sitemap_exclude": false,
		"locale": "en",
		"projects": [],
		"seo": 1,
		"localizations": [
			5,
			6
		]
	},
	{
		"id": 2,
		"name": "Deep Learning",
		"slug": "deep-learning",
		"description": "Deep Learning, these days booming due to its great versatility in many projects and technological solutions; we have also had our meetings in recent years, especially in the area of my master's thesis.",
		"createdAt": "2022-10-08T12:35:38.097Z",
		"updatedAt": "2022-10-08T14:19:09.303Z",
		"sitemap_exclude": false,
		"locale": "en",
		"projects": [],
		"seo": 4,
		"localizations": [
			8,
			7
		]
	},
	{
		"id": 3,
		"name": "Front-End Development",
		"slug": "front-end-development",
		"description": "All the projects related to Back-End Development that I have done throughout my career as a systems and computer engineer.",
		"createdAt": "2022-10-08T12:35:38.111Z",
		"updatedAt": "2022-10-08T14:25:45.202Z",
		"sitemap_exclude": false,
		"locale": "en",
		"projects": [],
		"seo": 7,
		"localizations": [
			10,
			9
		]
	},
	{
		"id": 4,
		"name": "Videogames",
		"slug": "video-games",
		"description": "Videogames are my passion, since my time at university I have worked on small projects in order to learn and become familiar with the industry, I even got to work as a game developer; here are some of those projects.",
		"createdAt": "2022-10-08T12:35:38.127Z",
		"updatedAt": "2022-10-08T14:35:18.321Z",
		"sitemap_exclude": false,
		"locale": "en",
		"projects": [],
		"seo": 10,
		"localizations": [
			11,
			12
		]
	}
]
```

As you can see, it shows the `localizations` but it does not export them.

<img width="1312" alt="Screen Shot 2022-10-08 at 17 58 50" src="https://user-images.githubusercontent.com/5034215/194713798-261e1f27-a18b-4ded-800c-157f22bc639b.png">

Here you can see I switched the language to Turkish, and it is still exporting all English data.

Why is this happening?

**Comment by SalahAdDin** [comment] 2022-10-08 16:04
> @Baboo7 Well, it is not clear even to me.
> 
> I'm trying to export my data and it always comes in English:
> 
> ```
> [
> 	{
> 		"id": 1,
> 		"name": "Back-End Development",
> 		"slug": "back-end-development",
> 		"description": "All the projects related to Back-end Development that I have done throughout my career as a systems and computer engineer.",
> 		"createdAt": "2022-10-08T12:35:38.019Z",
> 		"updatedAt": "2022-10-08T14:10:05.640Z",
> 		"sitemap_exclude": false,
> 		"locale": "en",
> 		"projects": [],
> 		"seo": 1,
> 		"localizations": [
> 			5,
> 			6
> 		]
> 	},
> 	{
> 		"id": 2,
> 		"name": "Deep Learning",
> 		"slug": "deep-learning",
> 		"description": "Deep Learning, these days booming due to its great versatility in many projects and technological solutions; we have also had our meetings in recent years, especially in the area of my master's thesis.",
> 		"createdAt": "2022-10-08T12:35:38.097Z",
> 		"updatedAt": "2022-10-08T14:19:09.303Z",
> 		"sitemap_exclude": false,
> 		"locale": "en",
> 		"projects": [],
> 		"seo": 4,
> 		"localizations": [
> 			8,
> 			7
> 		]
> 	},
> 	{
> 		"id": 3,
> 		"name": "Front-End Development",
> 		"slug": "front-end-development",
> 		"description": "All the projects related to Back-End Development that I have done throughout my career as a systems and computer engineer.",
> 		"createdAt": "2022-10-08T12:35:38.111Z",
> 		"updatedAt": "2022-10-08T14:25:45.202Z",
> 		"sitemap_exclude": false,
> 		"locale": "en",
> 		"projects": [],
> 		"seo": 7,
> 		"localizations": [
> 			10,
> 			9
> 		]
> 	},
> 	{
> 		"id": 4,
> 		"name": "Videogames",
> 		"slug": "video-games",
> 		"description": "Videogames are my passion, since my time at university I have worked on small projects in order to learn and become familiar with the industry, I even got to work as a game developer; here are some of those projects.",
> 		"createdAt": "2022-10-08T12:35:38.127Z",
> 		"updatedAt": "2022-10-08T14:35:18.321Z",
> 		"sitemap_exclude": false,
> 		"locale": "en",
> 		"projects": [],
> 		"seo": 10,
> 		"localizations": [
> 			11,
> 			12
> 		]
> 	}
> ]
> ```
> 
> As you can see, it shows the `localizations` but it does not export them.
> 
> <img alt="Screen Shot 2022-10-08 at 17 58 50" width="1312" src="https://user-images.githubusercontent.com/5034215/194713798-261e1f27-a18b-4ded-800c-157f22bc639b.png">
> 
> Here you can see I switched the language to Turkish, and it is still exporting all English data.
> 
> Why is this happening?

Actually, I understood: I'm choosing export relations as `id`, but in such case, there is no any way to export the other entities(localization/seo); It would be nice if you put a warning message about this.

**Comment by Baboo7** [comment] 2022-10-08 19:30
Hey @SalahAdDin I released a new version 1.16.1 that introduces a json v2 export/import mechanism. I tshows more stable results and v1 is now deprecated. You can give it a try, it should solve your issue

**Comment by SalahAdDin** [comment] 2022-10-09 12:13
> Hey @SalahAdDin I released a new version 1.16.1 that introduces a JSON v2 export/import mechanism. It shows more stable results and v1 is now deprecated. You can give it a try, it should solve your issue

How does it work?

**Comment by Baboo7** [comment] 2022-10-09 15:39
You just have to select the export format json v2 from the export modal and you're good :)

**Comment by SalahAdDin** [comment] 2022-10-09 17:19
> You just have to select the export format json v2 from the export modal and you're good :)

No no, what's the difference between both versions? I checked them and... the second version is less clear to me.

**Comment by Baboo7** [comment] 2022-10-09 21:40
I updated the doc where you can find details about the new file structure. Basically, entries are flattened per collection instead of being nested
