### ISSUE TITLE
[FEATURE] Roles for ADMINISTRATION PANEL 

### ISSUE THREAD

**Issue by qhoirulanwar** [Baboo7/strapi-plugin-import-export-entries#123] opened 2023-06-01 06:19 UTC
**Is your feature request related to a problem? Please describe.**
I'm always disappointed when I can't manage who can access the Import Export plugin page

**Describe the solution you'd like**
I want it to be resolved immediately on the settings page -> ADMINISTRATION PANEL -> Roles

**Additional context**
![Web capture_1-6-2023_131659_localhost](https://github.com/Baboo7/strapi-plugin-import-export-entries/assets/22901097/3c51f599-2026-4c5e-a601-3acc1aaddf6f)

**Comment by Baboo7** [comment] 2023-06-02 11:45
I'm closing this issue since it's a duplicate of #9

**Closed by Baboo7** 2023-06-02 11:45 UTC
Labels: feature:prioritized
