### ISSUE TITLE
[BUG] Postgres sequence id not updating after importing data

### ISSUE THREAD

**Issue by LefBoutham** [Baboo7/strapi-plugin-import-export-entries#71] opened 2022-10-24 09:00 UTC
**Describe the bug**
There's an issue after importing data, and then trying to add new single data entries manually – Strapi throws a `duplicate key value violates unique constraint` error. The reason is that Postgres doesn't update the primary key sequence after a bulk import, so it has to be updated via a script according to: https://github.com/strapi/strapi/issues/12493#issuecomment-1044724834

**To Reproduce**

1. Set up Strapi with Postgres DB and install the plugin
2. Import data for any collection type by clicking the `import` button
3. After data import, try adding a single entry manually
4. See `duplicate key value violates unique constraint error` from console

**Expected behavior**
Postgres should update the `primary key sequence` after the import, so it won't need to be manually triggered as explained in: https://github.com/strapi/strapi/issues/12493#issuecomment-1044724834

**Comment by Baboo7** [comment] 2022-10-24 09:48
Hey @LefBoutham ! Thanks for the feedback. This issue has been mentioned previously here https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/37 and on the discord of the project.

I'm closing this one for now but I'll prioritize this issue since it's mentioned a lot

**Comment by Baboo7** [comment] 2022-10-28 21:25
Version `1.17.1` is out and fixes the issue 🚀

**Comment by kickstyl3** [comment] 2022-11-09 14:32
The issue remains unsolved on the latest version of the plugin

**Comment by Baboo7** [comment] 2022-11-09 17:09
Did you use json v2 format?

**Comment by kickstyl3** [comment] 2022-11-10 08:02
@Baboo7 Yes, we used JSON v2 and tried different deepness levels, but the issue remains

**Comment by Baboo7** [comment] 2022-11-10 08:57
That's surprising. I tested on a postgres db and the sequence is updated correctly after importing. 

Technically, knex is used to run the raw query mentioned in the linked thread for each imported collection type. 

What version of postgres do you use? Is there any error displayed in the logs of the server?

**Comment by alucav** [comment] 2023-01-01 20:22
this also occurs if you PUT or ADD a component to a collection with a component too quickly with Postgres db.

To reproduce:

Create Collection with repeatable component A, then add another component B with multiple fields to component A.

So:

Collection 
      Component A (Repeatable)
           Component B (Single with Multiple Fields)
 
Create several component A entries via the API.
Then remove each component A via PUT request, one at a time.

The requests will come in too quickly and Postgres will attempt to run them simultaneously and throw an ID conflict on Component B.

`
returning "id" - duplicate key value violates unique constraint 
`

**Comment by ShaheryarK** [comment] 2023-02-10 08:04
@Baboo7 I am also facing this issue when importing data in a content type using Postgres, it will be great if I could know some work around it.

**Comment by Baboo7** [comment] 2023-04-23 12:42
@alucav @kickstyl3 @ShaheryarK @LefBoutham version 1.19.0 is out with a better and reliable way to import components/repeatable components/dynamic zones

**Closed** 2023-04-23 14:41 UTC
