### ISSUE TITLE
[BUG] On JSON import, new objects are created instead of matching existing ones.

### ISSUE THREAD

**Issue by JWesorick** [Baboo7/strapi-plugin-import-export-entries#31] opened 2022-08-09 07:29 UTC
**Describe the bug**
When importing from JSON, new objects are created instead of matching existing ones.

**To Reproduce**
My json/schema looks like this.

```json
[
  {
    "name": "Recommended", 
    "members": [
      { "playlist": { "slug": "awesome-mix-vol-two" } },
    ]
  }
]
```

Where the outermost object is a "collection" with "members", a repeatable component, and each member has a relation to a "playlist".

**Expected behavior**
When I import a JSON file like the structure above I expect a new Collection object to be made with a list of Members matching existing Playlists based on the given slug. Instead new Playlist objects are created with just the slug field filled in.

The docs say

> the relation is searched in db. If an entry is found, it is updated with the provided data. Otherwise, it is created.

so my guess is that both the Collection object and Member object do not exist yet, so the entire thing including a new playlist is created. I would expect a new Collection and a new Member, but match the existing Playlist with that slug.

**Screenshots**

![Screen Shot 2022-08-09 at 2 29 12 PM](https://user-images.githubusercontent.com/801062/183590518-53a3eaa0-2c32-4198-a12b-a728a9937509.png)

**Comment by Baboo7** [comment] 2022-08-11 17:25
Hey @JWesorick thanks for the report. This actually the expected behavior since entries are searched by `id`. If only a `slug` property is provided in the imported object then `playlist`s are created

**Comment by Baboo7** [comment] 2022-08-11 17:29
I created [an issue](https://github.com/Baboo7/strapi-plugin-import-export-entries/issues/33)  to make the doc clearer

**Comment by Baboo7** [comment] 2022-08-15 17:44
@JWesorick I updated the [doc](https://github.com/Baboo7/strapi-plugin-import-export-entries#importing-data). I'm closing this issue for now

**Comment by Baboo7** [comment] 2022-09-25 15:54
Hey @JWesorick, FYI I just published version `1.15.0` where v2 of export/import has been implemented. It's a beta still but it showed more stable results than the v1 on the test data I used. Export v2 is accessible in the export modal by selecting the export format `JSON (v2)` / import v2 is detected automatically from the structure of the provided data file. This new version `1.15.0` does NOT introduce breaking changes so v1 is still accessible and behaving as in previous version 😉 

With this new file structure, it will be easier and more maintainable to have custom id fields per collection types. Since this feature is in high demand, it will be prioritized in a near future.

I would love to have your feedback on this new version. Feel free to join the [discord server](https://discord.gg/cGRJh7M7) of the project I just opened 😌

**Comment by JWesorick** [comment] 2022-10-20 03:16
@Baboo7 Thanks for the new release! I was just able to check this out and start using it. Right now there are still some issues. I'll post them here for now but can create new issues if you'd like.

Strapi v4.3.4
strapi-plugin-import-export-entries 1.16.2

- creating blank objects
  - I turned those validations off to see what would happen. It works but also creates an empty object for each object in the import, each time I run it. So 

- not accounting for required field & unique field
  - I'm trying to match objects on a `slug` field. It has "required field"  and "unique field" checked under advanced settings. During import it is throwing errors as if those fields are not set.

![Screen Shot 2022-10-20 at 9 57 59 AM](https://user-images.githubusercontent.com/801062/196847462-c22aab82-154e-4a99-b346-4969db8a2c86.png)
![Screen Shot 2022-10-20 at 10 01 53 AM](https://user-images.githubusercontent.com/801062/196847477-7ef3f232-be86-4060-879c-a1a145412930.png)
![Screen Shot 2022-10-20 at 9 59 40 AM](https://user-images.githubusercontent.com/801062/196847483-9b14eb98-2e5d-4aab-a6ed-e22bd94ef17c.png)

**Comment by sharkfin009** [comment] 2022-10-25 16:31
So I just got the hang of this myself. 
Not sure if I understand what you are saying above, but if you want to link a newly created record to an existing record, you need to have the id and include that as a field. And the 'version 2' json format requires the id as a key also. 

The unique identifier field is something different, I just successfully used it to prevent any duplication when creating records.  It is usefull because I when importing lots of them, some seem to fail (350 records). On my second run, only the ones which where not yet added where added thanks to the unique field option.

This is a really usefull plugin , i would love to help improve the documentation if thats ok and I can find the time ;)

**Comment by sharkfin009** [comment] 2022-10-26 01:50
@Baboo7 one thing that I think could be made clearer is how creating new records differs from updating records. I had success with the v1 JSON format for creation , and v2 seems to be for updating? Yet v1 is deprecated?

**Comment by sharkfin009** [comment] 2022-10-26 09:14
ah ok sorry , read the docs again now.  This actually says it all:
`{
  "version": 2, // required for the import to work properly.
  "data": {
    // Each collection has a dedicated key in the `data` property.
    "api::collection-name.collection-name": {
      // Sub keys are `id`s of imported entries and values hold the data of the entries to import.
      "1": {
        "id": 1
        //...
      },
      "2": {
        "id": 2
        //...
      }
    },
    "api::other-collection-name.other-collection-name": {
      "1": {
        "id": 1,
        // Relations are specified by `id`s.
        "collectionAbove": [1]
        //...
      },
      "2": {
        "id": 2,
        "collectionAbove": [1, 2]
        //...
      }
    },
    // Import medias.
    "plugin::upload.file": {
      "1": {
        "id": 1
        //...
      },
      "2": {
        "id": 2
        //...
      }
    },
    // Import components.
    "my.component": {
      "1": {
        "id": 1
        //...
      },
      "2": {
        "id": 2
        //...
      }
    }
  }
}`

**Comment by sharkfin009** [comment] 2022-10-26 09:22
So you set up relations by referring to the model of the parent model, within your JSON.
My question is this: does it work as mentioned under v1, ie that the id is searched for in the db , and if found , then its an update, otherwise it's a creation?

**Comment by Baboo7** [comment] 2022-10-28 18:14
That's a good question. The referred entry should exist otherwise an error is thrown. Since we only know the id of the referred entry, no entry is created if not found

**Comment by JWesorick** [comment] 2022-11-11 08:57
I guess one more thing, uploads (`plugin::upload.file`) seem to only match on the existing id. Taking that into account different collections you may want to match on different keys. Ex. `slug` for a page and `name` for a file upload. I think the deprecated v1 allowed matching media on `name`.

**Comment by Baboo7** [comment] 2022-11-13 17:40
I plan on having a feature to match entries by custom id fields for each collection independently. We would also have multiple id fields specified that whould be used one after the other. For example we could look for an entry by `name`, then by `slug`, lastly by `id` before creating the entry if none have been found

**Comment by Baboo7** [comment] 2022-11-14 08:46
We're on the same page. It would be defined in the json itself

**Comment by Baboo7** [comment] 2023-04-23 12:40
@JWesorick have a look at version 1.19.0, and at the README (Config section). idField can now be specified per collection in the collection schema

**Closed by Baboo7** 2023-04-23 12:40 UTC
