### ISSUE TITLE
[BUG] Click check "export format" strapi server error

### ISSUE THREAD

**Issue by DanielZhui** [Baboo7/strapi-plugin-import-export-entries#83] opened 2022-11-24 08:14 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/44571398/203728539-d49cc753-5d89-4662-a74d-29a851cf30ff.png)

**Additional context**

**Comment by Baboo7** [comment] 2023-04-23 14:38
I could not reproduce the issue with the very few information you gave. I'm closing this issue for now.

**Closed by Baboo7** 2023-04-23 14:38 UTC
